### ISSUE TITLE
Package missing from Universe

### ISSUE THREAD

**Issue by dmcd** [AppliedIS/dcos-geoserver#2]
Is there a public universe repository for this package? I'm trying to follow these steps but I'd like to avoid having to setup my own universe server if possible.

https://docs.mesosphere.com/1.8/usage/repo/

**Comment by gisjedi** [comment]
@dmcd We are working on getting this pulled in as a first class package in the universe. I haven't done much with DCOS 1.8, so I'm not sure this will work out-of-the-box, but you can use our forked repo that contains what we are using to test this package on 1.7 here: https://github.com/appliedis/universe/tree/geoserver-2.x

**Comment by gisjedi** [comment]
@dmcd I know this has been awhile, but we are finally getting close to having this in the official DC/OS Universe. Here is the PR that is going through final review:

https://github.com/mesosphere/universe/pull/494

Once approved, I'll let you know.

**Comment by ryadav88** [comment]
@dmcd @gisjedi GeoServer is now available in DC/OS Universe!

**Comment by dmcd** [comment]
Awesome, I look forward to trying it out, cheers!
